version: '3.9'
services:
  api_db:
    image: postgres:14-alpine
    container_name: fin_api_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
     - api_db
    depends_on:
      - api_db

volumes:
  pgdata:
    driver: local
