version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: fin_api_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
